### ISSUE TITLE
Error if datetime columns are empty/null

### ISSUE THREAD

**Issue by MRB60** [rqlite/sqlalchemy-rqlite#13]
I get the following error unless I set defaults in datetime columns:

`venv/lib/python3.8/site-packages/pyrqlite/extensions.py", line 111, in <lambda> 'DATETIME': lambda x: x.replace('T', ' ').rstrip('Z')
`

Defaults must be set.

**Comment by MRB60** [comment]
Sqlite3 itself accepts empty/null/None Datetime columns. Problem occured when I switched from Sqlite3 to Rqlite. However, it was easy fixed by setting default timestamp for column.

**Comment by zmedico** [comment]
Please test with pyrqlite 2.2.3 which has the fix from https://github.com/rqlite/pyrqlite/pull/62.

**Comment by zmedico** [comment]
Please reopen if you think this is not the same as https://github.com/rqlite/pyrqlite/issues/51 fixed by https://github.com/rqlite/pyrqlite/pull/62.
