### ISSUE TITLE
Python3/Sqlalchemy 2.0: util.py2k not found

### ISSUE THREAD

**Issue by MRB60** [rqlite/sqlalchemy-rqlite#15]
py2k is no longer in python3/sqlalachemy 2.0.
`/venv/lib/python3.8/site-packages/sqlalchemy_rqlite/pyrqlite.py", line 50, in SQLiteDialect_rqlite
 if not util.py2k:
`
Works fine if statement is just removed. Is python2 still supported?

**Comment by zmedico** [comment]
I think it would be pretty safe to drop python2 support now. I see that sqlalchemy dropped it in https://github.com/sqlalchemy/sqlalchemy/commit/36e7aebd8d6faac77570403e99f9aa7b2330fa59.

**Comment by otoolep** [comment]
Is there anything specific we need to do, @zmedico ?

**Comment by zmedico** [comment]
I see that the sqlalchemy pysqlite plugin still has the description_encoding attribute here:

https://github.com/sqlalchemy/sqlalchemy/blob/rel_2_0_13/lib/sqlalchemy/dialects/sqlite/pysqlite.py#L499

So, #17 preserves it.
