### ISSUE TITLE
sqlalchemy.orm.exc.StaleDataError: expected to delete 1 row(s); Only 0 were matched.

### ISSUE THREAD

**Issue by AlexRoidl** [rqlite/sqlalchemy-rqlite#6]
I am using flask with sqlalchemy-rqlite and with Python3
When I use the clear() I get:
sqlalchemy.orm.exc.StaleDataError: DELETE statement on table 'books_authors' expected to delete 1 row(s); Only 0 were matched.
Any idea how to solve this issue? Thanks a lot!
I can provide further details if needed.

**Comment by AlexRoidl** [comment]
It seems like overall the DELETE command seems to be called twice, but I don't know exactly where…

**Comment by zmedico** [comment]
Oh, I've just noticed my test case does trigger this warning message:
```
sqlalchemy/lib/sqlalchemy/orm/persistence.py:1066: SAWarning: DELETE statement on table 'foo' expected to delete 1 row(s); 0 were matched.  Please set confirm_deleted_rows=False within the mapper configuration to prevent this warning.
  (table.description, expected, rows_matched)
```

**Comment by zmedico** [comment]
Please test https://github.com/rqlite/pyrqlite/commit/cb2f6af7547771bd072cb3bc28a27e996847648e.

**Comment by AlexRoidl** [comment]
THANKS SO MUCH!!
This saved my day!!
