### ISSUE TITLE
pip install fail

### ISSUE THREAD

**Issue by tiantian1645** [rqlite/sqlalchemy-rqlite#8]
Hello:
    when i use pip install from pypi, I found it failed.
```
ERROR: Could not find a version that satisfies the requirement sqlalchemy_rqlite (from versions: none)
ERROR: No matching distribution found for sqlalchemy_rqlite
```

**Comment by otoolep** [comment]
@zmedico -- any ideas?

**Comment by mengyyy** [comment]
```
pip3 install -U git+https://github.com/rqlite/pyrqlite.git git+https://github.com/rqlite/sqlalchemy-rqlite.git
```

**Comment by zmedico** [comment]
> ```
> pip3 install -U git+https://github.com/rqlite/pyrqlite.git git+https://github.com/rqlite/sqlalchemy-rqlite.git
> ```

It works for me after a052c0d39d50851b768f0bd7df2a13074aff0b9b.
